// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetCurrentData():Promise<types.ExcelData>;

export function GetHeaders():Promise<Array<string>>;

export function ImportExcel(arg1:string,arg2:string):Promise<types.ImportResult>;
