// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackQueue(arg1) {
  return window['go']['main']['App']['BackQueue'](arg1);
}

export function GetCurrentData() {
  return window['go']['main']['App']['GetCurrentData']();
}

export function GetHeaders() {
  return window['go']['main']['App']['GetHeaders']();
}

export function ImportExcel(arg1, arg2) {
  return window['go']['main']['App']['ImportExcel'](arg1, arg2);
}

export function NextQueue(arg1) {
  return window['go']['main']['App']['NextQueue'](arg1);
}

export function ReCallQueue(arg1) {
  return window['go']['main']['App']['ReCallQueue'](arg1);
}

export function SkipQueue(arg1) {
  return window['go']['main']['App']['SkipQueue'](arg1);
}

export function SpeakVietnamese(arg1) {
  return window['go']['main']['App']['SpeakVietnamese'](arg1);
}

export function UpdateRow(arg1, arg2) {
  return window['go']['main']['App']['UpdateRow'](arg1, arg2);
}
