// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function BackQueue(arg1:number):Promise<types.ImportResult>;

export function GetCurrentData():Promise<types.ExcelData>;

export function GetHeaders():Promise<Array<string>>;

export function ImportExcel(arg1:string,arg2:string):Promise<types.ImportResult>;

export function NextQueue(arg1:number):Promise<types.ImportResult>;

export function ReCallQueue(arg1:number):Promise<types.ImportResult>;

export function SkipQueue(arg1:number):Promise<types.ImportResult>;

export function SpeakVietnamese(arg1:string):Promise<void>;

export function UpdateRow(arg1:number,arg2:Record<string, any>):Promise<types.ImportResult>;
