// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentData() {
  return window['go']['main']['App']['GetCurrentData']();
}

export function GetHeaders() {
  return window['go']['main']['App']['GetHeaders']();
}

export function ImportExcel(arg1, arg2) {
  return window['go']['main']['App']['ImportExcel'](arg1, arg2);
}
